### ISSUE TITLE
Each provider should be own repo/npm module

### ISSUE THREAD

**Issue by bencevans** [webcast-io/iostreams#4]

**Comment by paulbjensen** [comment]
Could you describe what you mean by provider?

**Comment by bencevans** [comment]
A provider is something that takes the config and returns a stream.

They're currently stored in
https://github.com/webcast-io/iostreams/tree/master/providers

E.g S3 Provider adds the functionality of opening read and write streams
based on a S3 URL.

**Comment by paulbjensen** [comment]
ok, cool.
